### ISSUE TITLE
AOSP安卓11保存后报错

### ISSUE THREAD

**Issue by dxuser1919** [Eynnzerr/YuukaTalk#25]
我点击保存后就显示错误，但是确实是保存了
version: 1.1.1
java.io.IOException: Operation not permitted
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at com.eynnzerr.yuukatalk.ui.page.talk.TalkViewModel$saveTalkAsJson$1.invokeSuspend(TalkViewModel.kt:616)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@72ba9, Dispatchers.IO]

**Comment by Eynnzerr** [comment]
意思是虽然报了这个错，但是图片/存档确实保存了，也能找到对应文件吗？
可以提供一下手机型号和当前的保存路径（在设置页面里）～

**Comment by dxuser1919** [comment]
保存为图片时没有报错，但是保存工程/保存为文件时报错了，我已确认文件路径存在，以下是设备信息：
手机型号:TablePC 
​手机品牌:TablePC 
​Android系统版本:11
​Android系统api等级:30

**Comment by Eynnzerr** [comment]
根据报错信息，你没有为app授予访问你的文件保存路径的权限，或者你曾经授予了，但是因为某种原因权限被收回了。你可以尝试在设置中更改文件导出路径，根据引导重新选择一个合法的路径并授予权限并重试；或者，如果不需要存档文件，直接关闭自动备份功能，就应该可以正常保存工程。
你可以先尝试以上方法，如果没有用，还请麻烦你提供更多信息，比如你当前的编辑器设置。

**Comment by dxuser1919** [comment]
换了个存储目录，问题解决了，谢谢

**Comment by dxuser1919** [comment]
现在目前情况是某些工程文件保存会报错，而其他工程文件保存不会报错
例：“114514”的工程可以保存，但是“1919810”的工程保存时会报错

**Comment by Eynnzerr** [comment]
可以给出你设置的存储目录看看~
