### ISSUE TITLE
安卓10（vivoY52s V2057A）保存时报错

### ISSUE THREAD

**Issue by GcMhRen** [Eynnzerr/YuukaTalk#8]
第一次写issue，我写的有问题的话请告诉我
1.0.0版本时保存会直接闪退
1.0.1版本保存会出现新对话报错，内容如下:
java.io.FileNotFoundException: /storage/emulated/0/Pictures/screenshot-1702401269621.png: open failed: EACCES (Permission denied)
java.io.FileNotFoundException: /storage/emulated/0/Pictures/screenshot-1702401269621.png: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at com.eynnzerr.yuukatalk.utils.ImageUtils.writeBitmap(ImageUtils.kt:127)
	at com.eynnzerr.yuukatalk.utils.ImageUtils.saveBitMapToDisk(ImageUtils.kt:121)
	at com.eynnzerr.yuukatalk.ui.page.talk.TalkPageKt$TalkPage$5$5$2$1$imageUri$1.invokeSuspend(TalkPage.kt:486)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:10

>

**Comment by Eynnzerr** [comment]
你好。这是由于Android10以下，系统并未强制启用分区存储，而YuukaTalk采用分区存储以避免向用户申请存储权限。

这个bug将在v1.0.2中修复。
